sudo: false
language: ruby
rvm:
  - 2.5.0
  - 2.4.3
  - 2.3.6
gemfile:
  - gemfiles/rails_4.2.gemfile
  - gemfiles/rails_5.0.gemfile
  - gemfiles/rails_5.1.gemfile
  - gemfiles/rails_5.2.gemfile
  - gemfiles/rails_head.gemfile
before_install:
  - gem install bundler -v 1.16.1
script:
  - bundle exec rspec
